version: '3.9'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  client:
    image: neofaruq/react-docker-client:1.0.0
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client/
    stdin_open: true
    ports:
      - "3000:3000"

  api:
    image: neofaruq/node-docker-server:1.0.0
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server/
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo: 
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes:  
      - mongo-data:/data/db
      
volumes:
  mongo-data: 
    driver: local